jobs:

- job: Linux
  timeoutInMinutes: 0

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11' 
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkDestinationDirectory: 
  - script: wget https://nightly.tlapl.us/dist/tla2tools.jar
    displayName: Get (nightly) TLC
  - script: |
      set MYVAR=foo
      set
    displayName: Set a variable and then display all
    env:
      aVarFromYaml: someValue
  - script: java -version
    workingDirectory: $(Agent.BuildDirectory)
    displayName: Run TLC

